### ISSUE TITLE
Segmentation fault when running examples

### ISSUE THREAD

**Issue by benedictsaunders** [mcaroba/cl-MDS#1]
I compiled both `cl-MDS` and `quippy` as per their instructions with the following:

- GCC 11.2.0
- OpenBLAS 0.3.14
- ScaLAPACK 2.1.0

with `QUIP_ARCH=linux_x86_64_gfortran_openmpi+openmp`

all while keeping the same conda environment activated. Then when it comes to running the examples, running the following:

`$ python example_atoms_simple.py`
`$ python example_advanced.py`
`$ python example_dist_matrix.py`
`$ python fast_demo.py`

which each yields something akin to

`Computing descriptors:   0.0%[zx81:65974:0:65974] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xffffffff9843d85c)` 
(just with different memory addresses)

This cannot be a memory issue, as the machine I am attempting to run it on has 500 GB RAM.

`example_hypersphere.py` and `test_coord.py` in the tests directory, appear to run without issue.

**Comment by mcaroba** [comment]
Have you got previous experience with QUIP/Quippy? Have you tried building the descriptors with Quippy, i.e., without using it via cl-MDS? Hopefully we can narrow it down to either a Quippy or cl-MDS issue.

**Comment by benedictsaunders** [comment]
Sorry, the fault is with me; I was using an outdated version of QUIP. With compilation of the latest version, the examples complete successfully.

**Comment by mcaroba** [comment]
Good to know. Do not hesitate to open a new issue if you experience any problems or have feedback to share.
